webtalk_init -webtalk_dir /home/almul0/Universidad/ityst/17-18/TFG/TFG-Code/VHDL/MultiStageHalfBandInterpolator/MultiStageHalfBandInterpolator.sim/sim_1/behav/xsim/xsim.dir/tb_MultiStageHalfBandInterpolator_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 14 18:43:03 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2348494" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e34ccb87-acda-4973-8296-bf3289d7b3c6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "01e2fbf89067455b99f0eb7ae0bcb558" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "120" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux unstable (sid)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2993.071 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "13" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "44 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "4 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "10" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "10" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.43_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "194672_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1780806507 -regid "" -xml /home/almul0/Universidad/ityst/17-18/TFG/TFG-Code/VHDL/MultiStageHalfBandInterpolator/MultiStageHalfBandInterpolator.sim/sim_1/behav/xsim/xsim.dir/tb_MultiStageHalfBandInterpolator_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/almul0/Universidad/ityst/17-18/TFG/TFG-Code/VHDL/MultiStageHalfBandInterpolator/MultiStageHalfBandInterpolator.sim/sim_1/behav/xsim/xsim.dir/tb_MultiStageHalfBandInterpolator_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/almul0/Universidad/ityst/17-18/TFG/TFG-Code/VHDL/MultiStageHalfBandInterpolator/MultiStageHalfBandInterpolator.sim/sim_1/behav/xsim/xsim.dir/tb_MultiStageHalfBandInterpolator_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
